DROP DATABASE  IF EXISTS NOTE_EXAM;
CREATE DATABASE NOTE_EXAM ;
USE NOTE_EXAM ;

DROP TABLE IF EXISTS ETUDIANT ;
CREATE TABLE ETUDIANT(
    id_etudiant INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    numero_etudiant VARCHAR(255) ,
    nom_etudiant VARCHAR (255),
    prenom_etudiant VARCHAR(255),
    date_de_naissance_etudiant VARCHAR(255),
    id_class INT
) ;

DROP TABLE IF EXISTS DEVOIR ;
CREATE TABLE DEVOIR (
    id_dev INT AUTO_INCREMENT PRIMARY KEY,
    moy_dev FLOAT,
    id_matiere INT
) ;
DROP TABLE IF EXISTS CLASSE ;
CREATE TABLE CLASSE (
    id_class INT AUTO_INCREMENT PRIMARY KEY,
    nom_class VARCHAR (255)
) ;
DROP TABLE IF EXISTS MATIERE ;
CREATE TABLE MATIERE (
    id_matiere INT AUTO_INCREMENT PRIMARY KEY,
    nom_matiere VARCHAR(255)
) ;
DROP TABLE IF EXISTS POSSEDER ;
CREATE TABLE POSSEDER (
    id_etudiant INT,
    id_dev INT ,
    PRIMARY KEY(id_etudiant,id_dev)
) ;
DROP TABLE IF EXISTS OBTENIR ;
CREATE TABLE OBTENIR (
     id_etudiant INT  ,
     id_matiere INT ,
     note_examen FLOAT,
     moyenne_generale FLOAT ,
     PRIMARY KEY (id_etudiant,id_matiere)

);
ALTER TABLE ETUDIANT ADD CONSTRAINT FK_ETUDIANT_id_class FOREIGN KEY (id_class) REFERENCES CLASSE (id_class) ;
ALTER TABLE DEVOIR ADD CONSTRAINT FK FOREIGN KEY (id_matiere) REFERENCES MATIERE (id_matiere) ;
ALTER TABLE POSSEDER ADD CONSTRAINT AK FOREIGN KEY (id_etudiant) REFERENCES ETUDIANT (id_etudiant);
ALTER TABLE POSSEDER ADD CONSTRAINT BK FOREIGN KEY (id_dev) REFERENCES DEVOIR (id_dev);
ALTER TABLE OBTENIR  ADD CONSTRAINT CK FOREIGN KEY (id_etudiant) REFERENCES ETUDIANT (id_etudiant) ;
ALTER TABLE OBTENIR ADD CONSTRAINT DK FOREIGN KEY (id_matiere) REFERENCES MATIERE (id_matiere) ;
 

